---
title: "Regression Analysis—Interactions—Reviewing Editor"
author: "Dakota Murray"
output: html_notebook
---

### Set parameters for the name and extension of the figure
```{r}
figure_name <- "fig_si.X"
figure_extension <- ".png"

path_to_data <- "https://www.dropbox.com/s/97im2cayb1trlax/formatted_elife.csv?dl=1"
```

```{r message=FALSE, warning=FALSE}
# Load required packages
library(tidyverse)
library(lmtest)
library(tidyr)
library(stargazer)
library(sjPlot)
library(sjlabelled)
library(sjmisc)
library(grid)
library(gridExtra)
```

### Load the required data
```{r message=FALSE, warning=FALSE}
# Replace this string 
elife <- read.csv(path_to_data)

elife$fa_continent <- relevel(elife$fa_continent, ref = "North America")
elife$la_continent <- relevel(elife$la_continent, ref = "North America")

elife$composition <- relevel(elife$composition, ref = "Mixed")

elife$la_institution_rank <- with(elife, ifelse(la_institution_rank == "Top", "Top", "Sandard/Unranked/Unknown"))

elife$submission_year <- elife$submission_year - 2012
dim(elife)
```

### Define initial and full submissions
```{r}
full_submissions <- elife %>% filter(full_decision_made)
full_submissions$included <- with(full_submissions, la_continent != "Antarctica" & fa_continent != "Antarctica" & !is.na(la_gender) & la_gender != "UNK" & composition != "Uncertain" & !is.na(la_reviewer_dist) & !is.na(la_reviewer_dist_zero) & !is.na(la_institution_rank) & !is.na(la_continent) & !is.na(fa_gender))
```


### Construct the interaction variable
```{r}
assign_interaction_term = function(la_gender, bre_gender) {
  if (la_gender == "M") {
    if (bre_gender == "M") {
      return("Male Author, Male Rev. Editor")
    } else if (bre_gender == "F") {
      return("Male Author, Female Rev. Editor")
    } else {
      return(NA)
    }
  } else if (la_gender == "F") {
    if (bre_gender == "M") {
      return("Female Author, Male Rev. Editor")
    } else if (bre_gender == "F") {
      return("Female Author, Female Rev. Editor")
    } else {
      return(NA)
    }
  } else {
    return(NA)
  }
}

full_with_inter <- full_submissions %>%
  filter(!is.na(bre_gender) & composition_adj != "Uncertain") %>%
  rowwise() %>%
  mutate(
    author_bre_interaction = assign_interaction_term(la_gender, bre_gender)
  ) %>%
  ungroup() %>%
  mutate(author_bre_interaction = as.factor(author_bre_interaction)) %>%
  mutate(la_bre_dist_zero = la_bre_dist == 0)

table(full_with_inter$author_bre_interaction)
```


### Construct the model for full submissions with interactions
```{r}
full_model <- glm(accepted ~ submission_year + submission_type + fa_gender + la_institution_rank + la_continent + I(la_bre_dist/ 1000000) + I(la_reviewer_dist / 1000000) + la_reviewer_dist_zero + la_bre_dist_zero + author_bre_interaction + composition_adj, data = subset(full_with_inter, included), family = "binomial")
summary(full_model)
```


### Run ANOVA on the model...
```{r}
anova(full_model, test = "Chisq")
```


### Construct the plot for full submissions
```{r}
full.cov.labels = c(
               "submission_year" = "Submission Year", 
               "submission_typeSR" = "Submission Type = SR", 
               "submission_typeTR" = "Submission Type = TR", 
               "fa_genderM" = "First Author is Male",
               "fa_genderUNK" = "First Author is Unknown Gender",
               "la_institution_rankTop" = "Last Author Inst. Top 50",
               "la_continentAfrica" = "Last author from Africa",
               "la_continentAsia" = "Last author from Asia",
               "la_continentEurope" = "Last author from Europe",
               "la_continentOceania" = "Last author from Oceania",
               "la_continentSouth America" = "Last author from South America",
               "I(la_bre_dist/1e+06)" = "Dist. between author and rev. editor (1000km)",
               "I(la_reviewer_dist/1e+06)" = "Sum of author-reviewer distance (1000km)",
               "la_reviewer_dist_zeroTRUE" = "Total dist. between author and reviewers is zero",
               "la_bre_dist_zeroTRUE" = "Dist. between author and rev. editor is zero",
               "author_bre_interactionFemale Author, Male Rev. Editor" = "Last author female - male rev. editor",
               #"author_bre_interactionFemale Author, Female Rev. Editor" = "Last author female - female rev. editor",
               "author_bre_interactionMale Author, Female Rev. Editor" = "Last author male - female rev. editor",
               "author_bre_interactionMale Author, Male Rev. Editor" = "Last author male - male rev. editor",
               "composition_adjAll Women" = "All Female Reviewers",
               "composition_adjMixed" = "Mixed Reviewers"
               )


full_reg_plot <- plot_model(full_model, 
           vline.color = "black", 
           rm.terms = c("fa_genderUNK"),
           sort.est = TRUE, 
           show.values = TRUE, 
           value.offset = .3, 
           axis.labels = full.cov.labels,
           wrap.labels = 100, # basically, don't wrap the labels, squeeze them all in
           title = "Acceptance of full submissions",
           axis.lim = c(0.1, 10)) +
  theme_bw()

full_reg_plot
```

```{r}
library(stargazer)
stargazer(full_model,
          covariate.labels = full.cov.labels,
          t.auto = F,
          p.auto = F,
          ci = T, 
          align = T,
          apply.coef = exp,
          type = "latex",
          font.size = "tiny",
          style = "ajs")
```

### Arrange the plots
```{r}
regressions_interactions <- grid.arrange(initial_reg_plot, full_reg_plot, ncol = 2)
```

### Save the plot
```{r}
name <- paste0("~/Dropbox/eLife/elife-analysis/figures/main/", figure_name, figure_extension)
ggsave(name, plot = regressions_interactions, height = 5, width = 10)
```